### ISSUE TITLE
Root repo README is missing any information about API key auth method

### ISSUE THREAD

**Issue by wolendranh** [Triple-Whale/triple-whale-public-apis#3]
hi! 

Current README is missing any information about API key auth format, it only provide brief overview of OAUTH method. 

```
To get started with the Triple Whale API, just follow these basic steps:

Register your app with Triple Whale
Receive your OAuth credentials from Triple Whale
Execute the OAuth flow and grant access to your shop
Retrieve the OAuth token and make authenticated requests to the API
```
To get information about API key developers have to go into nodejs example and search it there. API key information is located only in nodejs example [README](https://github.com/Triple-Whale/triple-whale-public-apis/blob/master/examples/node/README.md)

It would be nice to have this kind of general important info on main README.

Thank you in advance!

**Comment by wkatkinson** [comment]
Although there was a brief section about API keys in the readme, more info was added (from the node example Readme).
